name: gsc-report
on:
  schedule:
    - cron: '0 22 * * 0' # This is 07:00 JST on Monday (JST = UTC+9)
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm ci
    - env:
        GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
        GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
        WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
      run: node main.js
